### PR TITLE
merge PupQL into pup

### PR DESCRIPTION
**Pull request by ayhid**
disable subscriptions in favor of refetchQueries

### CODE REVIEW

**Comment by cleverbeagle** [comment]
Thanks for putting this together @ayhid, taking a look now :)

**Comment by cleverbeagle** [comment]
Looks good, adding to 2.1.0 release!

**Comment by ayhid** [comment]
@cleverbeagle sorry, but it breaks some features like users list for example, I am investigating to find out why.

**Comment by cleverbeagle** [comment]
It looks like the `ApolloLink.split()` needs to be removed here: https://github.com/cleverbeagle/pup/blob/a3081770d5d7001f6156b30d67c7704e5eff848b/startup/client/apollo.js#L34

**Comment by ayhid** [comment]
Yes that's what I found out, pushing an update asap.

**Comment by cleverbeagle** [comment]
Merged by hand, thanks @ayhid.

**Pull request closed without merging**
