### PR TITLE
Update Meteor to 2.7.1

### PR DESCRIPTION
**Pull request by fredmaiaarantes**

### CODE REVIEW

**Comment by auBusinessDaD** [comment]
Very nice, thanks for this. I don't suppose you have also added Apollo subscriptions as well?

**Comment by fredmaiaarantes** [comment]
> Very nice, thanks for this. I don't suppose you have also added Apollo subscriptions as well?

Hey! I haven't, I tried to not change any of the current behavior and not add any features right now. Only updated Meteor.

I'm not sure if the author will merge it but I'm planning to keep my fork anyway.

My plan is to gradually update the other packages. Next steps are to upgrade bootstrap css from 3 to 4 (already started it) and react router from 4 to 5.

**Comment by auBusinessDaD** [comment]
Well, I will for sure be using your updated version. Thanks for sharing, and would certainly be interested in the other updates you make.

If you happen to have a version of this updated with subscriptions, that would be greatly appreciated - I am still learning it in general.

**Comment by rglover** [comment]
@fredmaiaarantes thank you for putting this together.

**Pull request merged**
