### PR TITLE
Import methods on client

### PR DESCRIPTION
**Pull request by zodern**

### CODE REVIEW

**Comment by tomscholz** [comment]
Can you explain a little bit further why did you make the changes? What is this fixing, adding? :)

**Comment by cleverbeagle** [comment]
@tomscholz https://github.com/cleverbeagle/pup/issues/53

**Comment by cleverbeagle** [comment]
Looking at this again I agree with @tomscholz. The `both` would give a clear hint as right now you have to ask "why is that in there by itself?" @zodern would you be willing to make this change (just move `/imports/startup/api.js` into `/imports/startup/both/api.js` and correct the other imports)?

**Comment by zodern** [comment]
@tomscholz @cleverbeagle it does make more sense. I moved the file.

**Pull request closed without merging**
