### PR TITLE
Add a base template allowing for much smaller and DRYer html email templates

### PR DESCRIPTION
**Pull request by MichelFloyd**
Currently in Pup each html email template (verifyEmail, welcome, resetPassword) duplicates the email boilerplate.

1. This makes each template very long and harder to edit
1.  If you want to change the email boilerplate you have to do it in multiple files

This PR introduces a new base template that *wraps* a much smaller template for each of the core transactional email types used by Pup. It also automatically feeds in variables that are used by the base template so that a developer creating a new template doesn't have to remember to pass additional variables needed by the base template.

This PR builds on my previous PR (#140) which involved moving the application name and related settings from code to settings.

### CODE REVIEW

**Comment by tomscholz** [comment]
Could you revert the changes that you made to the `package-lock.json` file? It seems unnecessary since you haven't added any new dependencies.

**Comment by MichelFloyd** [comment]
Done. I'm not sure why the package-lock file got so skinnyed down during my edits but now it's back to the b02cd6577d27810c2ec043a25f396c7dd0f836c9 version.

**Comment by cleverbeagle** [comment]
Merging this. Ended up using a slightly fancier template for the base (the one we use for CB emails). Thanks @MichelFloyd :)

**Comment by MichelFloyd** [comment]
Awesome! Glad this was useful.

**Pull request closed without merging**
